inherit:
    - base.yaml

training:
    task: ode_ivp_case1plus
    data: ode_ivp_case1plus
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    learning_rate: 0.0001
eval:
    task: ode_ivp_case1plus
    data: ode_ivp_case1plus
    evaltype: continuous_output
    batch_size: 64
    n_dims: 20
    n_points: 41


out_dir: ../models12/ode_ivp_case1plus  #

wandb:
    name: "eval_mode"

trained_id: 282a9fa2-268d-4397-a03d-fca6ce75675f
# python src/evaluate_ode.py --config src/conf/ode_ivp_case1plus_eval.yaml >> running_logs/ode_ivp_case1plus_eval.log 2>&1 &