inherit:
    - base.yaml

training:
    task: ode_ivp_case2
    data: ode_ivp_case2
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000

model:
    n_dims: 50
eval:
    task: ode_ivp_case2
    data: ode_ivp_case2
    evaltype: continuous_output
    batch_size: 64
    n_dims: 50
    n_points: 41
    draw_diff: true
    draw_steperr: true
    draw_relativeh_steperr: true
out_dir: ../models12/ode_ivp_case2  #

wandb:
    name: "eval_mode"
    
trained_id: 83537d68-2a0b-4203-bae8-2436022f22a5

set_device: 0

# case2 设置更大范围的t输入 [t_e_st,t_e_ed]=[1,2]
# 可否设置输出训练出 不同的 y 的输出？
# python src/evaluate_ode.py --config src/conf/ode_ivp_case2_eval_0303.yaml >> running_logs/ode_ivp_case2_eval_0303.log 2>&1 &