inherit:
    - base.yaml

training:
    task: ode_ivp_case2
    data: ode_ivp_case2
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000
    learning_rate: 0.0001
    # resume_id: 9a20d467-9e5a-4883-9b98-2e4a141e55e3
    If_enhanced_loss: true
    keep_every_steps: 50000
    train_steps: 200001

model:
    n_dims: 50

out_dir: ../models12/ode_ivp_case2  #

wandb:
    name: "ode_ivp_case2_run1_enhancedloss_run_0303"

set_device: 1
# nohup python src/train.py --config src/conf/ode_ivp_case2.yaml >> running_logs/ode_ivp_case2_enhancedloss_run_0303.log 2>&1 &