inherit:
    - base.yaml

training:
    task: ode_ivp_case1plus
    data: ode_ivp_case1plus
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000
    learning_rate: 0.0001
    If_enhanced_loss: true
    keep_every_steps: 50000
    train_steps: 200001
    If_use_h: true

model:
    n_dims: 50

out_dir: ../models12/ode_ivp_case1plus_h_enhancedloss  #

wandb:
    name: "ode_ivp_case1plus_h_enhancedloss_run_015"

set_device: 0

# case2 设置更大范围的t输入 [t_e_st,t_e_ed]=[1,2]
# 可否设置输出训练出 不同的 y 的输出？
# nohup python src/train.py --config src/conf/ode_ivp_case1plus_h.yaml >> running_logs/ode_ivp_case1plus_h_enhancedloss_0317.log 2>&1 &