inherit:
    - base.yaml

training:
    task: ode_ivp_case2vec
    data: ode_ivp_case2
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000
    learning_rate: 0.0001
    If_enhanced_loss: true
    keep_every_steps: 50000
    train_steps: 200001
    If_use_h : False
    If_evalloss_in_train : True
    eval_loss_per_steps : 100
    num_eval_tasks : 1
    
model:
    n_dims: 50
    n_layer: 24

out_dir: ../models12/ode_ivp_case2vec_valid_layer24  #

wandb:
    name: "ode_ivp_case2_valid_layer24_02"

set_device: 0
# nohup python src/train.py --config src/conf/ode_ivp_case2vec_valid_layer24.yaml >> running_logs/ode_ivp_case2_valid_layer24_02.log 2>&1 &