inherit:
    - base.yaml

training:
    task: ode_ivp_case1
    data: ode_ivp_case1
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    learning_rate: 0.0001


out_dir: ../models12/ode_ivp_case1  #

wandb:
    name: "ode_ivp_case1_run1"
# case2 设置更大范围的t输入 [t_e_st,t_e_ed]=[1,2]
# 可否设置输出训练出 不同的 y 的输出？
# nohup python src/train.py --config src/conf/ode_ivp_case1.yaml >> running_logs/ode_ivp_case1_new.log 2>&1 &