inherit:
    - base.yaml

training:
    task: ode_ivp_case2vec
    data: ode_ivp_case2
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000
        lr:
            schedule_type: "four_stage"
            start: 0.000001   # 1e-6
            firstup_end: 10000
            highlearn: 0.0003  # 3e-4
            highlearn_end: 50000
            downlearn_end: 150000 
            lowlearn: 0.00001  # 1e-5
            steadylearn: 0.000001  # 1e-6

    learning_rate: 0.0001
    If_enhanced_loss: true
    keep_every_steps: 50000
    train_steps: 3000001 # 原来为20000001 
    If_use_h : False
    If_evalloss_in_train : True
    eval_loss_per_steps : 100
    num_eval_tasks : 1
    resume_id : cf0e52d6-7902-425c-8ccb-f2d52004b686 # 如果要停止训练，直接kill 即可，如果要继续训练，再次运行 nohup等代码即可
    
model:
    n_dims: 50
    n_layer: 24

out_dir: ../models12/longrun_ode_ivp_case2_layer24  #

wandb:
    name: "longrun_ode_ivp_case2_layer24"

set_device: 0
# nohup python src/train.py --config src/conf/ode_ivp_longrun_ode_ivp_case2_layer24.yaml >> running_logs/longrun_ode_ivp_case2_layer24.log 2>&1 &