inherit:
    - base.yaml

training:
    task: ode_ivp_case2plus
    data: ode_ivp_case2
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 50
            inc: 3
            interval: 2000
    learning_rate: 0.0001
    If_enhanced_loss: true
    keep_every_steps: 50000
    train_steps: 200001


out_dir: ../models12/ode_ivp_case2plus  #

wandb:
    name: "ode_ivp_case2plus_enhancedloss_run_0303"


set_device: 0

# nohup python src/train.py --config src/conf/ode_ivp_case2plus.yaml >> running_logs/ode_ivp_case2plus.log 2>&1 &